eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
server:
  port: 8804
spring:
  application:
    name: feign-consumer
api:
  feiyanUrl: http://www.dzyong.top:3005
logging:
  com: debug

